# Generated by Django 5.2 on 2025-05-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('reset', 'Password reset'), ('login', 'Login')], max_length=6),
        ),
    ]
