# Generated by Django 5.2.8 on 2026-02-24 09:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVendorCredit',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('credit_note_number', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vendor_address', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_address', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('authorized', 'Authorized'), ('partially_applied', 'Partially Applied'), ('applied', 'Applied / Paid'), ('voided', 'Voided'), ('deleted', 'Deleted'), ('in_review', 'In Review'), ('under_approval', 'Under Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('txn_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('is_attachment', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='db.organization')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='db.vendor')),
            ],
            options={
                'verbose_name': 'historical vendor credit',
                'verbose_name_plural': 'historical vendor credits',
                'db_table': 'vendor_credit_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VendorCredit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vendor_address', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_address', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('authorized', 'Authorized'), ('partially_applied', 'Partially Applied'), ('applied', 'Applied / Paid'), ('voided', 'Voided'), ('deleted', 'Deleted'), ('in_review', 'In Review'), ('under_approval', 'Under Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('txn_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('is_attachment', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_credits', to='db.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_credits', to='db.vendor')),
            ],
            options={
                'db_table': 'vendor_credits',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVendorCreditItem',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Display order')),
                ('description', models.TextField(blank=True, null=True)),
                ('detail_type', models.CharField(choices=[('account_based', 'Account Based'), ('item_based', 'Item Based'), ('service', 'Service'), ('other', 'Other')], default='account_based', max_length=32)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('vendor_credit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='db.vendorcredit')),
            ],
            options={
                'verbose_name': 'historical vendor credit item',
                'verbose_name_plural': 'historical vendor credit items',
                'db_table': 'vendor_credit__item_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VendorCreditItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Display order')),
                ('description', models.TextField(blank=True, null=True)),
                ('detail_type', models.CharField(choices=[('account_based', 'Account Based'), ('item_based', 'Item Based'), ('service', 'Service'), ('other', 'Other')], default='account_based', max_length=32)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('vendor_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.vendorcredit')),
            ],
            options={
                'db_table': 'vendor_credit_items',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['vendor_credit', 'sequence'], name='vendor_cred_vendor__17eca3_idx')],
            },
        ),
    ]
