# Generated by Django 5.2.8 on 2026-03-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_historicalvendorcredit_vendorcredit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=10),
        ),
    ]
