# Generated by Django 5.2 on 2025-05-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_verificationtoken_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('finance', 'Finance User'), ('management', 'Management User')], default='super_admin', max_length=20),
        ),
    ]
