# Generated by Django 5.2 on 2025-05-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('INR', 'Indian Rupee (₹)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)')], default='USD', help_text='Default currency for financial calculations', max_length=3),
        ),
        migrations.AddField(
            model_name='organization',
            name='date_format',
            field=models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD-MM-YYYY', 'DD-MM-YYYY'), ('MM-DD-YYYY', 'MM-DD-YYYY')], default='MM/DD/YYYY', help_text='Date format to use throughout the application', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='enable_bill_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
    ]
