# Generated by Django 5.2 on 2025-05-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_organization_options_organization_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='enable_bill_approval',
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_format',
            field=models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD-MM-YYYY', 'DD-MM-YYYY'), ('MM-DD-YYYY', 'MM-DD-YYYY'), ('YYYY/MM/DD', 'YYYY/MM/DD')], default='MM/DD/YYYY', help_text='Date format to use throughout the application', max_length=10),
        ),
    ]
