# Generated by Django 5.2 on 2025-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_user_invited_by_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In-Review'), ('under_approval', 'Under Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
