# Generated by Django 5.2 on 2025-05-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_approvalaction_comment_alter_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='action_type',
            field=models.CharField(choices=[('under_approval', 'Under Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under_approval', max_length=20),
            preserve_default=False,
        ),
    ]
