# Generated by Django 5.2 on 2025-05-16 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_approvalaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='approval_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='approval_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_sent_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
