# Generated by Django 5.2 on 2025-05-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_approvalaction_approval_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvalaction',
            unique_together=set(),
        ),
    ]
