# Generated by Django 5.2 on 2025-05-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_alter_approvalaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_terms',
            field=models.CharField(choices=[('net15', 'Net\xa015'), ('net30', 'Net\xa030'), ('net45', 'Net\xa045'), ('due', 'Due\xa0on\xa0receipt')], default='net30', max_length=8, null=True),
        ),
    ]
