# Generated by Django 5.2 on 2025-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_alter_bill_payment_terms_alter_vendor_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]