# Generated by Django 5.2 on 2025-05-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_user_invited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('net15', 'Net 15'), ('net30', 'Net 30'), ('net45', 'Net 45'), ('due', 'Due on receipt')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('net15', 'Net 15'), ('net30', 'Net 30'), ('net45', 'Net 45'), ('due', 'Due on receipt')], max_length=8, null=True),
        ),
    ]