# Generated by Django 5.2.1 on 2025-06-05 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_remove_attachment_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
