# Generated by Django 5.2.1 on 2025-06-06 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_alter_approvalassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
