# Generated by Django 5.2.1 on 2025-06-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_alter_usernotificationpreference_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_type',
            field=models.CharField(blank=True, choices=[('sole_proprietor', 'Sole Proprietor'), ('partnership', 'Partnership'), ('llc', 'LLC'), ('s_corp', 'S-Corp'), ('c_corp', 'C-Corp'), ('nonprofit', 'Nonprofit'), ('government_agency', 'Government Agency'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, choices=[('accounting', 'Accounting & Bookkeeping'), ('legal', 'Legal Services'), ('retail', 'Retail'), ('ecommerce', 'E-commerce'), ('real_estate', 'Real Estate'), ('restaurants', 'Restaurants & Food Services'), ('construction', 'Construction & Contracting'), ('healthcare', 'Healthcare & Medical'), ('manufacturing', 'Manufacturing'), ('software', 'Software/SaaS'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
