# Generated by Django 5.2.1 on 2025-06-09 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_organization_business_type_organization_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.OneToOneField(blank=True, help_text='Primary address of the organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_address', to='db.address'),
        ),
    ]
