# Generated by Django 5.2.1 on 2025-06-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_historicaladdress_historicalapprovalconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_attachment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='is_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
