# Generated by Django 5.2.1 on 2025-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_bill_is_attachment_historicalbill_is_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='is_attachment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
