# Generated by Django 5.2.1 on 2025-06-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_historicalpurchaseorder_is_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='matching_type',
            field=models.CharField(choices=[('none', 'None'), ('two_way', '2-Way Match'), ('three_way', '3-Way Match')], default='none', help_text='Matching logic enabled for this organization (e.g., 2-way, 3-way)', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='matching_type',
            field=models.CharField(choices=[('none', 'None'), ('two_way', '2-Way Match'), ('three_way', '3-Way Match')], default='none', help_text='Matching logic enabled for this organization (e.g., 2-way, 3-way)', max_length=20),
        ),
    ]
