# Generated by Django 5.2.1 on 2025-06-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_historicalorganization_matching_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In-Review'), ('under_approval', 'Under Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In-Review'), ('under_approval', 'Under Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
