# Generated by Django 5.2.1 on 2025-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_historicalpurchaseorder_status_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorderitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quantity received against this line item', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quantity received against this line item', max_digits=12),
        ),
    ]
