# Generated by Django 5.2.1 on 2025-06-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_historicalpurchaseorderitem_received_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='po_counter', to='db.organization')),
            ],
            options={
                'db_table': 'purchase_order_counters',
            },
        ),
    ]
