# Generated by Django 5.2.1 on 2025-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_purchaseordercounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='purchaseordercounter',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_org_po_counter'),
        ),
    ]
