# Generated by Django 5.2.1 on 2025-06-12 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_alter_historicalpurchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'bill_counters',
            },
        ),
        migrations.RemoveConstraint(
            model_name='purchaseordercounter',
            name='unique_org_po_counter',
        ),
        migrations.AddField(
            model_name='billcounter',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_counter', to='db.organization'),
        ),
    ]
