# Generated by Django 5.2.1 on 2025-06-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_historicalmatchresult_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatchresult',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='db.organization'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='db.organization'),
        ),
    ]
