# Generated by Django 5.2.1 on 2025-06-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0044_historicalmatchresult_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='db.organization'),
        ),
    ]
