# Generated by Django 5.2.1 on 2025-06-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_alter_matchresult_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatchresult',
            name='is_quantity_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='is_quantity_posted',
            field=models.BooleanField(default=False),
        ),
    ]
