# Generated by Django 5.2.1 on 2025-06-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_historicalmatchresult_is_quantity_posted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billitem',
            options={'verbose_name': 'BillItem', 'verbose_name_plural': 'BillItems'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['line_number'], 'verbose_name': 'Purchase Order Item', 'verbose_name_plural': 'Purchase Order Items'},
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderitem',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
