# Generated by Django 5.2.1 on 2025-06-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_alter_billitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billitem',
            options={'ordering': ['line_number', 'id'], 'verbose_name': 'BillItem', 'verbose_name_plural': 'BillItems'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['line_number', 'id'], 'verbose_name': 'Purchase Order Item', 'verbose_name_plural': 'Purchase Order Items'},
        ),
        migrations.AddField(
            model_name='billitem',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbillitem',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['bill', 'line_number'], name='bill_items_bill_id_0247ac_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'line_number'], name='purchase_or_purchas_a3e1b4_idx'),
        ),
    ]
