# Generated by Django 5.2.1 on 2025-06-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_remove_historicalapprovalconfig_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalvendor',
            table='vendor_history',
        ),
    ]
