# Generated by Django 5.2.1 on 2025-06-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0050_alter_historicalvendor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalbill',
            table='bill_history',
        ),
        migrations.AlterModelTable(
            name='historicalbillitem',
            table='bill_item_history',
        ),
        migrations.AlterModelTable(
            name='historicalpurchaseorder',
            table='purchase_order_history',
        ),
        migrations.AlterModelTable(
            name='historicalpurchaseorderitem',
            table='purchase_order_item_history',
        ),
    ]
