# Generated by Django 5.2.1 on 2025-07-01 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_matchresult_unique_match_result_per_org_poitem_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMatrix',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description_score', models.FloatField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.bill')),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_rows', to='db.billitem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.purchaseorder')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.purchaseorderitem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'match_matrix',
                'indexes': [models.Index(fields=['bill_item', 'purchase_order_item'], name='match_matri_bill_it_efe8ed_idx'), models.Index(fields=['bill', 'purchase_order'], name='match_matri_bill_id_d283e0_idx')],
                'unique_together': {('bill_item', 'purchase_order_item')},
            },
        ),
    ]
