# Generated by Django 5.2.1 on 2025-07-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_matchmatrix_unique_matrix_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='matching_progress',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error')], default='not_started', help_text='Status of line-item matching against purchase order', max_length=60),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='matching_progress',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error')], default='not_started', help_text='Status of line-item matching against purchase order', max_length=60),
        ),
    ]
