# Generated by Django 5.2.4 on 2025-07-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0058_bill_is_duplicate_historicalbill_is_duplicate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bill',
            name='bills_organiz_8ef070_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['vendor', 'bill_number', 'organization'], name='bills_vendor__ad4895_idx'),
        ),
    ]
