# Generated by Django 5.2.4 on 2025-08-19 09:42

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0059_remove_bill_bills_organiz_8ef070_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('approval', 'Approval Required'), ('system', 'System Notification')], default='info', max_length=10)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_name', models.CharField(blank=True, help_text="Lowercase model name, e.g., 'bill', 'purchaseorder'.", max_length=50, null=True)),
                ('object_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of the referenced object (e.g., Bill.id or PurchaseOrder.id).', null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='approvalflow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'L4'), (5, 'L5')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvallog',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderitem',
            name='line_status',
            field=models.CharField(choices=[('open', 'Open'), ('partially_received', 'Partially Received'), ('closed', 'Closed')], default='open', help_text='Current lifecycle status of this purchase order line item', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderitem',
            name='pending_approval_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity pending approval before fulfillment', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='line_status',
            field=models.CharField(choices=[('open', 'Open'), ('partially_received', 'Partially Received'), ('closed', 'Closed')], default='open', help_text='Current lifecycle status of this purchase order line item', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='pending_approval_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity pending approval before fulfillment', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Total quantity ordered in this line item', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorderitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity physically received against this line item', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Total quantity ordered in this line item', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity physically received against this line item', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='approvalflow',
            unique_together={('organization', 'model_name', 'level')},
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'line_status'], name='purchase_or_purchas_01dbed_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'line_number'), name='uniq_line_per_po'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='db.organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'owner', 'is_read'], name='notificatio_organiz_6ded24_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'owner', 'is_important'], name='notificatio_organiz_19919d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'owner', 'is_deleted', 'created_at'], name='notificatio_organiz_5a29d6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'created_at'], name='notificatio_priorit_22e6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'owner', 'object_name', 'object_id'], name='notificatio_organiz_406bd5_idx'),
        ),
    ]
