# Generated by Django 5.2.4 on 2025-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0060_notification_alter_approvalflow_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='is_quantity_posted',
            new_name='received_qty_applied',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='reserved_qty_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='description_score',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['purchase_order_item'], name='match_resul_purchas_bb0649_idx'),
        ),
    ]
