# Generated by Django 5.2.4 on 2025-08-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0061_rename_is_quantity_posted_matchresult_received_qty_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvallog',
            name='level',
        ),
    ]
