# Generated by Django 5.2.4 on 2025-08-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0062_remove_approvallog_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvallog',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
