# Generated by Django 5.2.4 on 2025-09-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0063_approvallog_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='receipt_confirmation_enabled',
            field=models.BooleanField(default=False, help_text='Enable Lite User receipt request/confirmation workflow for this organization.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('finance_manager', 'Finance Manager'), ('lite_user', 'Lite User')], default='admin', max_length=20),
        ),
    ]
