# Generated by Django 5.2.4 on 2025-09-25 07:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0064_organization_receipt_confirmation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='receipt_comment',
            field=models.TextField(blank=True, help_text='Comment or note provided by the assigned receipt confirmer.'),
        ),
        migrations.AddField(
            model_name='bill',
            name='receipt_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('revoked', 'Revoked')], db_index=True, default='draft', help_text='Lifecycle of the external receipt confirmation request.', max_length=16),
        ),
        migrations.AddField(
            model_name='billitem',
            name='confirmed_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity confirmed by Lite User; must be <= quantity.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='receipt_comment',
            field=models.TextField(blank=True, help_text='Comment or note provided by the assigned receipt confirmer.'),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='receipt_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('revoked', 'Revoked')], db_index=True, default='draft', help_text='Lifecycle of the external receipt confirmation request.', max_length=16),
        ),
        migrations.AddField(
            model_name='historicalbillitem',
            name='confirmed_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity confirmed by Lite User; must be <= quantity.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='ReceiptConfirmationTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('completed', 'Completed')], db_index=True, default='active', max_length=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('remind_count', models.PositiveIntegerField(default=0)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_confirmation_tasks', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_tasks', to='db.bill')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(help_text="Must match the bill's organization.", on_delete=django.db.models.deletion.CASCADE, related_name='receipt_confirmation_tasks', to='db.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_receipt_confirmation_tasks', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'receipt_confirmation_tasks',
                'ordering': ['-assigned_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status', 'assigned_at'], name='receipt_con_organiz_850939_idx'), models.Index(fields=['bill', 'status'], name='receipt_con_bill_id_826cf6_idx'), models.Index(fields=['assignee', 'status'], name='receipt_con_assigne_3ce40a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('bill',), name='unique_active_receipt_confirmer_per_bill')],
            },
        ),
    ]
