# Generated by Django 5.2.4 on 2025-10-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0066_alter_address_created_by_alter_address_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('partial', 'Partial Match'), ('mismatch', 'Mismatch'), ('no_po', 'No PO'), ('exception', 'Exception')], db_index=True, default='no_po', help_text='Status of bill matching against purchase order', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('partial', 'Partial Match'), ('mismatch', 'Mismatch'), ('no_po', 'No PO'), ('exception', 'Exception')], db_index=True, default='no_po', help_text='Status of bill matching against purchase order', max_length=20),
        ),
    ]
