# Generated by Django 5.2.7 on 2025-11-24 09:58

import rever.db.models.attachment
import rever.utils.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0067_bill_match_status_historicalbill_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=1024, storage=rever.utils.storage_backends.S3MediaStorage(), upload_to=rever.db.models.attachment.custom_attachment_upload_path),
        ),
    ]
