# Generated by Django 5.2.8 on 2025-11-24 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0068_alter_attachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorEmbedding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', models.JSONField(help_text='Vector embedding of normalized vendor name as list of floats')),
                ('embedding_model', models.CharField(default='all-MiniLM-L6-v2', help_text='Sentence transformer model used for embedding', max_length=100)),
                ('normalized_name', models.CharField(help_text='Normalized vendor name used for embedding generation', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='db.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Embedding',
                'verbose_name_plural': 'Vendor Embeddings',
                'db_table': 'vendor_embeddings',
            },
        ),
    ]
