# Generated by Django 5.2.8 on 2025-11-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0069_vendorembedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorEmbedding',
        ),
    ]
