# Generated by Django 5.2.8 on 2025-11-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellidocs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrlog',
            name='document_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocrlog',
            name='ocr_engine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ocrlog',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
