# Generated by Django 5.2.8 on 2026-02-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_historicalvendorcredit_vendorcredit_and_more'),
        ('intellidocs', '0002_documentextraction_delete_billextraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentextraction',
            name='credit_note_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='vendor_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='db.vendorcredit'),
        ),
        migrations.AlterField(
            model_name='documentextraction',
            name='document_type',
            field=models.CharField(choices=[('bill', 'Bill'), ('purchase_order', 'Purchase Order'), ('vendor_credit', 'Vendor Credit')], default='bill', max_length=50),
        ),
    ]
