# Generated by Django 5.2.8 on 2025-11-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellidocs', '0003_billextraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billextraction',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='billextraction',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billextraction',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billextraction',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='billextraction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billextraction',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billextraction',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='billextraction',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
