FROM node:20-alpine
RUN apk add --no-cache libc6-compat 

# Set working directory
WORKDIR /app

# Copy the entire monorepo structure
COPY . .

RUN yarn global add turbo
# Install dependencies using workspace
RUN yarn install

# Make sure next is in the path - include both root and web node_modules
ENV PATH=/app/node_modules/.bin:/app/web/node_modules/.bin:$PATH

CMD ["yarn", "dev"]
