FROM node:24-alpine AS base

# Add Corepack + pnpm activation (only once for all stages)
RUN corepack enable \
    && corepack prepare pnpm@latest --activate


# BUILD
FROM base AS builder
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app

# Install Turbo CLI globally

COPY . .

RUN pnpm dlx turbo prune --scope=web --docker



FROM base AS installer

RUN apk add --no-cache libc6-compat
WORKDIR /app

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

# Install dependencies with pnpm
RUN pnpm install --frozen-lockfile

# Build the project
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json

# In Next.js, environment variables that start with NEXT_PUBLIC_ are embedded into the JavaScript bundle at build time, not at runtime. 
ARG NEXT_PUBLIC_API_BASE_URL=""
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

ENV NEXT_TELEMETRY_DISABLED=1
ENV TURBO_TELEMETRY_DISABLED=1

RUN pnpm dlx turbo run build --filter=web



FROM base AS runner
WORKDIR /app

# Install wget for health check
# RUN apk add --no-cache wget
ENV NEXT_TELEMETRY_DISABLED=1
ENV TURBO_TELEMETRY_DISABLED=1

# In Next.js, environment variables that start with NEXT_PUBLIC_ are embedded into the JavaScript bundle at build time, not at runtime. 
ARG NEXT_PUBLIC_API_BASE_URL=""
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

# Copy necessary files from installer stage
COPY --from=installer /app/web/package.json ./web/package.json
COPY --from=installer /app/web/.next ./web/.next
COPY --from=installer /app/web/public ./web/public
COPY --from=installer /app/node_modules ./node_modules
COPY --from=installer /app/web/node_modules ./web/node_modules

# Set the correct working directory
WORKDIR /app/web

# Start the Next.js application
CMD ["pnpm", "start"]

EXPOSE 3000
